Description: Deploy layers api to a single region
AWSTemplateFormatVersion: 2010-09-09
Resources:
  LayersAPI:
    Properties:
      Description: Layer version API
      EndpointConfiguration:
        Types:
          - EDGE
      Body:
        swagger: '2.0'
        basePath: /dev
        definitions:
          Empty:
            type: object
            title: Empty Schema
        paths:
          /get-layers:
            get:
              produces:
                - application/json
              x-amazon-apigateway-integration:
                uri: 'arn:aws:apigateway:us-west-1:lambda:path//2018-10-31/layers'
                passthroughBehavior: when_no_match
                responses:
                  default:
                    statusCode: '200'
                httpMethod: GET
                credentials: LambdaReadLayers
                type: aws
              responses:
                '200':
                  schema:
                    $ref: '#/definitions/Empty'
                  description: 200 response
            options:
              produces:
                - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    $ref: '#/definitions/Empty'
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                passthroughBehavior: when_no_match
                responses:
                  default:
                    statusCode: '200'
              consumes:
                - application/json
        host: cv7dr82zff.execute-api.us-west-2.amazonaws.com
        schemes:
          - https
        info:
          title: LayerAPI
          version: '2019-02-06T01:20:23Z'
    Type: 'AWS::ApiGateway::RestApi'
  DomainLayersAPI:
    Properties:
      CertificateArn: >-
        arn:aws:acm:us-east-1:146318645305:certificate/57cd1444-5869-4572-9c22-0870ea1a3e9a
      EndpointConfiguration:
        Types:
          - EDGE
      DomainName: !Join 
        - .
        - - !Ref 'AWS::Region'
          - layers.iopipe.com
    Type: 'AWS::ApiGateway::DomainName'